config/routes.rb
Sanman::Application.routes.draw do



  devise_for :users

  get "/home", to: 'pages#home'
  get "/aboutus", to: 'pages#aboutus'
  get "/electronic_manufacturing", to: 'pages#electronic_manufacturing'
  get "/products", to: 'pages#products'
  get "/rfq", to: 'pages#rfq'
  get "/careers", to: 'pages#careers'
  get "/contact_us", to: 'pages#contact_us'


  resources :users, :only => [:index]
  resources :profiles, :only => [:show, :edit, :index, :update]


  match '/Join Us', :to => 'devise/registrations#new'
  match '/Sign in', :to => 'devise/sessions#new'
  match '/Sign out', :to => 'devise/sessions#destroy'

  root :to => 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :Full_name, :permanent_address,:business_address,:company_address,:contact_number, :avatar


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  belongs_to :user

  def has_attached_file(name, options = {})
    HasAttachedFile.define_on(self, name, options)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  #config.mailer_sender = "sbhattacharya.bagchi@gmail.com"
  has_one :profile
  after_create :build_profile

  def build_profile
    self.create_profile.save
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def aboutus
    @title = "About Us"
  end

  def design_services
    @title = "Design Service"
  end

  def electronic_manufacturing
    @title = "Electronic Manufacturing"
  end

  def products
    @title = "Products"
  end

  def rfq
    @title = "RFQ"
  end

  def careers
    @title = "Careers"
  end

  def contact_us
    @title = "Contact Us"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 # before_filter :authenticate_user!

  def show
    @profile= current_user.profile
  end


  def edit
    @title = "Profile"
    @profile= current_user.profile
  end

  def update
    @profile= current_user.profile
    a= params[:profile]
    if @profile.update_attributes(a)
      flash[:success] = "Profile Updated."                                            #After delete the params check the difference between create and update
      redirect_to @profile                                                               #  Parameters: {"utf8"=>"✓", "authenticity_token"=>"KPJGSVoW2naygRG1HFKCLmOtyZdold+zyfKadUMzZcA=", "user"=>{"sufix"=>"miss", "first_name"=>"addf", "last_name"=>"vcvjhgjh", "email"=>"dfgfhgk", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up", "id"=>"8"}
    else
      @title = "Edit profile"
      render 'edit'
    end
  end

  def index
    @profiles=Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  #UserMailer.registration_confirmation(@user).deliver
  def index
    @users = User.all
    @profiles=Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  private
  def currect_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(&user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.transliterate("errors.messages.not_saved",
                                  :count => resource.errors.count,
                                  :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-error">
      <h4>Error! not able to save.</h4>
      <ul class="devise_error">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact Point:: <%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">

        <div id="header">
            <!-- header start here -->
            <h1><span class="blue-text"></span>Contact Point</h1>
            <!-- logo -->
            <%#<%= image_tag("logo.png", :alt => "Sanman", :class => "round") %>
            <%#<img src= "/home/tanmay/Desktop/IMG_2914.JPG" alt="Contact Point">%>
      ‌      <!-- logo end -->
        </div>
      ‌
        <div id="menu" class="menuitem">
            <ul>
              <li><a><%= link_to "Home",'/home' %></a></li>
              <li><a><%= link_to "About Us",'/aboutus' %></a></li>
              <li><a><%= link_to "Design Services",'#' %></a></li>
              <li><a><%= link_to "Electronic Manufacturing",'/electronic_manufacturing' %></a></li>
              <li><a><%= link_to "Products",'/products' %></a></li>
              <li><a><%= link_to "RFQ",'/rfq' %></a></li>
              <li><a><%= link_to "Careers",'/careers' %></a></li>
              <li><a><%= link_to "Contact Us",'/contact_us' %></a></li>

            </ul>
        </div><!--menu end-->‌
        <aside>
        <div id="leftmenu">
            <h3>Links</h3>
                <ul>
                    <li><a href="browse.html">Porduct Details</a></li>
                    <li><a href="browse.html">Data Sheet</a></li>
                    <% if user_signed_in? %>
                      <li><%= link_to "Profile", '/profiles/edit' %></li>
                      <li><%= link_to "Seetings",edit_user_registration_path %></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    <% else %>
                      <li><%= link_to "Sign in",'/users/sign_in' %></li>
                      <li ><%= link_to "Join Us", '/users/sign_up' %></li>

                    <% end %>

                    <%#<% if current_user.admin? && signed_in? %>
                      <%#<li><a><%= link_to "All Users", '/users' %><%#</a></li>
                    <% end %>
                </ul>
        </div>
        </aside>
        <!--leftmenu end-->

        <div id="content" section class="container">
            <%= yield %>
            <!--CONTENT HERE-->
            </section>
        </div><!--content end-->

        <%#<section class="container">
            <%= yield %>
       <%# </section>%>

    </div>
</body>
</html>

app/views/pages/aboutus.html.erb
<h1>Pages#aboutus</h1>
<p>Find me in app/views/pages/aboutus.html.erb</p>

app/views/pages/careers.html.erb
<h1>Pages#careers</h1>
<p>Find me in app/views/pages/careers.html.erb</p>

app/views/pages/contact_us.html.erb
<div style="width:750px;padding-left:15px;"><!--main div start-->
  <h3>Contact Us</h3>
  <p>Please use this form to contact a member of our website team</p>
  <%#<form method="post" action="somescript.php">%>
    <p>
      <label for="name">Full Name:</label>
      <input type="text" name="name">
    </p>
    <p>
      <label for="email">Email Address: </label>
      <input type="text" name="email">
    </p>
    <p>
      <label for="phone">Phone Number: </label>
      <input type="text" name="phone">
    </p>
    <p>
      <label for="call">Best Time To Call: </label>
      <input type="radio" name="time" value="morning" checked>Morning
      <input type="radio" name="time" value="noon">Noon
      <input type="radio" name="time" value="evening">Evening
    </p>
    <p>
      <label for="budget">Budget: </label>
      <select type="list" name="budget">
        <option>--Please Select--</option>
        <option value="100-500">100 - 499</option>
        <option value="500-1000">500 - 1000</option>
        <option value="1000-2000">1000 - 2000</option>
        <option value="2000+">2000+</option>
        <option value="not sure">Not Sure</option>
      </select>
    </p>
    <p>
      <label for="call">Services Needed: (Check all that apply) </label>
    <table>
      <tr>
        <td><input type="checkbox" name="services" value="Audio Devise">Audio Devise</td>
        <td><input type="checkbox" name="services" value="Video Devise">Video dDevise</td>
      </tr>
      <tr>
        <td><input type="checkbox" name="services" value="SMPS">SMPS</td>
        <td><input type="checkbox" name="services" value="UPS">UPS</td>
      </tr>
      <tr>
        <td><input type="checkbox" name="services" value="PCB Soldering">PCB Soldering</td>
        <td><input type="checkbox" name="services" value="PCB designing">PCB Designing</td>
      </tr>
    </table>
    </p>
    <p>
      <input type="submit" value="Submit Inquiry">
    </p>
  </form>
</div><!--main div end-->

app/views/pages/design_services.html.erb
<h1>Pages#design_services</h1>
<p>Find me in app/views/pages/design_services.html.erb</p>

app/views/pages/electronic_manufacturing.html.erb
<h1>Pages#electronic_manufacturing</h1>
<p>Find me in app/views/pages/electronic_manufacturing.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/products.html.erb
<div><!--main div start-->
  <h3>Product Details</h3>
    <p>Please Compare with your Requirement</p>
    <%#<form method="post" action="somescript.php">%>
    <p>
    <p>
        <label for="products">Products: </label>
            <select input type="list" name="products">
            <option>--Please Select--</option>
            <option value="Audio Devise">Audio Devise</option>
            <option value="500-1000">500 - 1000</option>
            <option value="1000-2000">1000 - 2000</option>
            <option value="2000+">2000+</option>
            <option value="not sure">Not Sure</option>
        </select>
    </p>
    <table class="dev-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Specification</th>
                <th>Rate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Aaaa</td>
                <td>Bbbb</td>
                <td>120</td>
            </tr>
            <tr>
                <td><a href="profile.html">Mark Judge</a></td>
                <td>Fall River</td>
                <td>html5, css</td>
            </tr>
        </tbody>
    </table>
</div><!--main div end-->

app/views/pages/rfq.html.erb
<h1>Pages#rfq</h1>
<p>Find me in app/views/pages/rfq.html.erb</p>

app/views/profiles/_show.html.erb
<table class="profile" summary="Profile information" >
  <%= flash[:success]= " Your Profile" %>
  <tr>
    <td class="sidebar round">
      <h1>
        <%= image_tag @profile.avatar.url(:thumb) %>
      </h1></td>
    <td class="sidebar round">
      <h1>
        <%= @profile.Full_name %>  </h1>
      <%= link_to 'Edit Profile', edit_profile_path(@profile) %>

    </td>
  </tr>







</table>

app/views/profiles/edit.html.erb
<h1> Edit Profile</h1>

<%= form_for @profile, :html => { :multipart => true } do |f| %>
    <%= f.text_field :Full_name %>
    <%= f.text_field :permanent_address %>
    <%= f.text_field :business_address %>
    <%= f.text_field :company_address %>
    <%= f.text_field :contact_number %>
    <%= f.file_field :avatar %>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
    <%= link_to 'Show', profile_path(@profile) %>

<% end %>

app/views/profiles/show.html.erb
<%= render 'show' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>PhoneNo:</b>
  <%= @user.email %>
</p>



<%= link_to 'Products List', '/products' %>